TerrenceMM2/dewey

- package.json
Running `git run deploy` from the server will build react files and push to the current branch.
> deployment script

- controllers/bookController.js
- models/Book.js
- models/User.js
- models/index.js
- routes/bookRoutes.js
- server.js
- services/bookService.js
> initial structure for routes/controllers/services

- README.md
> updates deployment tech

- src/controllers/userController.js
- src/routes/userRoutes.js
- src/services/userService.js
> extracts user validate() into userService

- src/models/User.js
Removes primary key parameters from columns in user model that aren't necessary.
> removes primary key bug in user model

- src/loaders/Middleware.js
- src/loaders/Routing.js
- src/server.js
Extracts routes to their own class for initialization.
Moves passport initialization into middleware class.
> extracts routes to class for initialization

- src/config/passport.js
- src/models/index.js
- src/services/bookService.js
- src/services/userService.js
updates various const * = require() statements to import statements && var to const/let
> ES6 syntax updates

- client/src/components/Scanner/Scanner.js
- package-lock.json
- package.json
- src/lib/Error.js
- src/loaders/Connection.js
- src/services/userService.js
> implements a top secret funciton

- client/src/App.js
- client/src/components/LoginForm/LoginForm.js
- client/src/index.js
- adds linear gradient to button styling
- adds box shadow to button styling
> button styling customized

- client/src/components/LoginForm/LoginForm.js
- client/src/components/RegisterForm/RegisterForm.js
- client/src/pages/Register.js
- adds styling to registration page
- minor style edits to login page to bring both pages in sync
> Registration page updates

- client/src/components/LoginForm/LoginForm.js
- client/src/components/RegisterForm/RegisterForm.js
Removes `100vh` from the login and register forms
> fixes page height and footer placement

- client/src/components/LoginForm/LoginForm.js
- client/src/components/PasswordForm/Action.js
- client/src/components/Search/Action.js
- client/src/utils/setAuthToken.js
setAuthToken and sets default axios headers
> adds setAuthToken

- .ebextensions/https-instance-securitygroup.config
Adds EB config to use HTTPS.
-   [ ] Bug fix (non-breaking change which fixes an issue)
> adds https rule to eb instance - take 1

- client/src/App.js
- client/src/pages/Dashboard.js
- bottom nav only shows when user is logged in
-   [ ] New feature (non-breaking change which adds functionality)
> fixes issue where the bottom nav showed when user was not logged in

- client/src/components/Navigation/Navigation.js
- enables logout
-   [ ] Bug fix (non-breaking change which fixes an issue)
> enables logout

- client/src/App.js
- client/src/components/Footer/index.js
fixes footer and bottom nav placement
-   [ ] New feature (non-breaking change which adds functionality)
> fixes footer and nav placement

- client/src/App.js
- client/src/components/LoginForm/LoginForm.js
- client/src/context/contexts/UserContext.js
- client/src/context/reducers/UserReducer.js
- client/src/pages/Account.js
- src/services/authService.js
- adds email, firstname, and lastname into jwt payload
- adds same details into usercontext on login and page refresh
-   [ ] Bug fix (non-breaking change which fixes an issue)
> display user profile on settings page

- client/src/components/Search/Scanner.js
- client/src/components/Search/SearchForm.js
- updates scanner button styling
-   [] New feature (non-breaking change which adds functionality)
> adds styling to scanner button

- src/config/nodemailer.js
Removes nodemailer.js from config.
-   [ ] New feature (non-breaking change which adds functionality)
> removes nodemailer.js from config

- src/loaders/Middleware.js
- src/routes/utilRoutes.js
-   [ ] New feature (non-breaking change which adds functionality)
> adds express static middleware and updates wildcard GET route

- client/src/pages/Library.js
- package-lock.json
- package.json
- src/loaders/Connection.js
Implements some CSS and a masonry layout for the library page
-   [ ] Bug fix (non-breaking change which fixes an issue)
> Adds basic library ui styling
